parameters:
  symfony_rollbar.event_listener.exception_listener.class: SymfonyRollbarBundle\EventListener\ExceptionListener
  symfony_rollbar.event_listener.error_listener.class: SymfonyRollbarBundle\EventListener\ErrorListener
  symfony_rollbar.provider.rollbar_handler.class: SymfonyRollbarBundle\Provider\RollbarHandler

services:
  symfony_rollbar.event_listener.exception_listener:
    class: SymfonyRollbarBundle\EventListener\ExceptionListener
    arguments: ["@service_container"]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: -100 }

  symfony_rollbar.event_listener.error_listener:
    class: SymfonyRollbarBundle\EventListener\ErrorListener
    arguments: ["@service_container"]
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  symfony_rollbar.provider.rollbar_handler:
    class: SymfonyRollbarBundle\Provider\RollbarHandler
    arguments: ["@service_container"]
